function [t,u_comp_lqr,u_phiobs,u_fullobs] = importU(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [T,U_COMP_LQR,U_PHIOBS,U_FULLOBS] = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [T,U_COMP_LQR,U_PHIOBS,U_FULLOBS] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [t,u_comp_lqr,u_phiobs,u_fullobs] = importfile('edge_u.csv',2, 673);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/05/01 10:50:31

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t = dataArray{:, 1};
u_comp_lqr = dataArray{:, 2};
u_phiobs = dataArray{:, 3};
u_fullobs = dataArray{:, 4};


