function [t5,x3_estimate,x3_phiobs,x3_fullobs] = importX3(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [T5,X3_ESTIMATE,X3_PHIOBS,X3_FULLOBS] = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   [T5,X3_ESTIMATE,X3_PHIOBS,X3_FULLOBS] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [t5,x3_estimate,x3_phiobs,x3_fullobs] = importfile('edge_x3.csv',2, 1506);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/05/01 18:22:19

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
t5 = dataArray{:, 1};
x3_estimate = dataArray{:, 2};
x3_phiobs = dataArray{:, 3};
x3_fullobs = dataArray{:, 4};


